The beginning of an openflow dissector.
svn path=/trunk/; revision=50513

Fix cut-and-pasteo found by a compiler warning.

Mark an unused parameter as unused.

svn path=/trunk/; revision=50515

Update dissection.

svn path=/trunk/; revision=50604

Fix some Dead Store (Dead assignement/Dead increment) Warning found by Clang

svn path=/trunk/; revision=50621

Fix warnings found by fix-encoding-args tools.(and remove some tabs also)

svn path=/trunk/; revision=50623

dissect OFPT_PACKET_IN.

svn path=/trunk/; revision=51633

Dissect more of openflow.

svn path=/trunk/; revision=51649

Fix
packet-openflow.c:318: warning: return type defaults to 'int'
packet-openflow.c: In function 'dissect_openflow_ofp_match_v_1_0':
packet-openflow.c:350: warning: control reaches end of non-void function

svn path=/trunk/; revision=51650

Fix compilation with Linux packet-openflow.c: In function 'dissect_openflow_pkt_out': packet-openflow.c:663:13: error: variable 'actions_len' set but not used [-Werror=unused-but-set-variable]

And make fix-encoding-args happy

svn path=/trunk/; revision=51651

Fix some Dead Store (Dead assignement/Dead increment) Warning found by Clang

svn path=/trunk/; revision=51737

Fix "malformed packet" and tidy up a bit.

svn path=/trunk/; revision=51740